#!/usr/bin/env python
"""Assemble the Stage-F M1 Kaggle bundle and record its integrity.

Copies `stage_e_recipe/kaggle/bundle/` (the frozen E0 bundle) to
`stage_f/followup/kaggle/bundle_f1m/`, applies the M1 patch (`m1_patch.py`) to
its `scripts/finetune_pilot.py`, rewrites `BUNDLE_MARKER.json`, and writes
`stage_f/followup/kaggle/source_integrity_f1m.json` listing every file with its
sha256 and whether it is byte-identical to the E0 bundle.

Verdict PASS only if exactly `scripts/finetune_pilot.py` and
`BUNDLE_MARKER.json` differ (`dataset-metadata.json` may additionally be
absent/added: it is removed here as stale and regenerated by `push_f1.py
dataset` at upload time).

Not a training run and not a Kaggle upload: this only writes `bundle_f1m/` and
`source_integrity_f1m.json`.

    python stage_f/followup/kaggle/build_bundle_f1m.py [--lam {0.1,1.0}]

--lam 0.1 (default) rebuilds bundle_f1m/ + source_integrity_f1m.json with
marker bundle stage-f-m1; --lam 1.0 builds bundle_f1m10/ +
source_integrity_f1m10.json with marker bundle stage-f-m1-lam1.
"""
from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
E0_BUNDLE = REPO / "stage_e_recipe" / "kaggle" / "bundle"

LAM_CONFIG = {
    0.1: {"bundle_dir": "bundle_f1m",
          "integrity": "source_integrity_f1m.json",
          "marker_bundle": "stage-f-m1",
          "experiment": "f1m",
          "bundle_rel": "stage_f/followup/kaggle/bundle_f1m"},
    1.0: {"bundle_dir": "bundle_f1m10",
          "integrity": "source_integrity_f1m10.json",
          "marker_bundle": "stage-f-m1-lam1",
          "experiment": "f1m10",
          "bundle_rel": "stage_f/followup/kaggle/bundle_f1m10"},
}

STAGE1_SHA = "3ae6fb3be6b2bda9287b325ccbe6d1397744c8f20ef5e56c046176d9f1a29be7"

# Files allowed to differ from the E0 bundle (or be absent/added):
# the patched recipe, the rewritten marker, and the upload-time metadata.
REQUIRED_DIFF = {"scripts/finetune_pilot.py", "BUNDLE_MARKER.json"}
OPTIONAL_DIFF = {"dataset-metadata.json"}


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def parse_args(argv: list[str] | None = None) -> float:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lam", type=float, default=0.1,
                    choices=(0.1, 1.0))
    return ap.parse_args(argv).lam


def main(lam: float = 0.1) -> None:
    if float(lam) not in LAM_CONFIG:
        sys.exit(f"BUILD FAIL: --lam must be 0.1 or 1.0, got {lam!r}")
    lam = float(lam)
    cfg = LAM_CONFIG[lam]
    BUNDLE = HERE / cfg["bundle_dir"]
    lam_literal = "0.1" if lam == 0.1 else "1.0"
    if not E0_BUNDLE.is_dir():
        sys.exit(f"BUILD FAIL: E0 bundle not found: {E0_BUNDLE}")
    sys.path.insert(0, str(HERE))
    import m1_patch

    if BUNDLE.exists():
        shutil.rmtree(BUNDLE)
    shutil.copytree(E0_BUNDLE, BUNDLE)

    # The one recipe intervention: M1 patch on the copy's finetune_pilot.py.
    fp = BUNDLE / "scripts" / "finetune_pilot.py"
    original = fp.read_text(encoding="utf-8")
    patched = m1_patch.apply(original, lam)
    # newline="" keeps LF: the ONLY difference from the E0 bundle copy must
    # be the declared edit, not the platform's line endings.
    fp.write_text(patched, encoding="utf-8", newline="")

    # Stale upload-time metadata is removed; push_f1.py writes it fresh.
    stale = BUNDLE / "dataset-metadata.json"
    stale_missing = not stale.exists()
    if stale.exists():
        stale.unlink()

    # Rewrite the marker; the init checkpoint is unchanged.
    marker = {
        "bundle": cfg["marker_bundle"],
        "campaign": "Stage F follow-up M1 pilot",
        "experiment": cfg["experiment"],
        "initialization": "Stage-1 pretrained ARM-P",
        "checkpoint_sha256": STAGE1_SHA,
        "recipe_source": "stage_b_armp/20260919T012646Z_tier2_seed1/scripts",
        "m1_lambda": lam,
        "patched": ["scripts/finetune_pilot.py (M1 distribution CE, "
                    f"Laplacian b=0.5 candidates, lambda={lam_literal})"],
        "training_authorized": False,
    }
    (BUNDLE / "BUNDLE_MARKER.json").write_text(json.dumps(marker, indent=2))

    # Integrity: every file hashed, compared against the E0 bundle.
    record: dict = {
        "bundle": cfg["bundle_rel"],
        "purpose": "Stage F follow-up M1 pilot Kaggle T4 execution bundle "
                   f"(lambda={lam_literal})",
        "source_bundle": "stage_e_recipe/kaggle/bundle (frozen E0)",
        "m1_lambda": lam,
        "files": {},
        "declared_deltas": {},
        "verdict": None,
    }
    e0_files = {p.relative_to(E0_BUNDLE).as_posix()
                for p in E0_BUNDLE.rglob("*") if p.is_file()}
    f1m_files = {p.relative_to(BUNDLE).as_posix()
                 for p in BUNDLE.rglob("*") if p.is_file()}
    ok = True
    for rel in sorted(e0_files | f1m_files):
        e0_p, f1m_p = E0_BUNDLE / rel, BUNDLE / rel
        if e0_p.is_file() and f1m_p.is_file():
            h0, h1 = sha256(e0_p), sha256(f1m_p)
            same = h0 == h1
            record["files"][rel] = {"sha256": h1, "e0_sha256": h0,
                                    "identical": same}
        elif f1m_p.is_file():
            record["files"][rel] = {"sha256": sha256(f1m_p),
                                    "e0_sha256": None, "identical": False,
                                    "note": "added (not in E0 bundle)"}
        else:
            record["files"][rel] = {"sha256": None,
                                    "e0_sha256": sha256(e0_p),
                                    "identical": False,
                                    "note": "removed from E0 bundle copy"}
    changed = {rel for rel, v in record["files"].items() if not v["identical"]}
    unexpected = changed - REQUIRED_DIFF - OPTIONAL_DIFF
    missing_required = REQUIRED_DIFF - changed
    verdict_ok = not unexpected and not missing_required
    record["declared_deltas"]["scripts/finetune_pilot.py"] = {
        "scope": "M1 INTERVENTION ONLY - training loss gains the Laplacian "
                 f"CE term (lambda={lam_literal}); optimizer, scheduler, data, "
                 "aug, validation, checkpointing, init, seed, determinism "
                 "unchanged",
        "edits": [{"why": why, "old": old.strip()[:120],
                   "new": new.strip()[:160]} for old, new, why in m1_patch.EDITS],
        "m1_lambda": lam,
        "unified_diff": list(difflib.unified_diff(
            original.splitlines(), patched.splitlines(),
            fromfile="bundle/scripts/finetune_pilot.py",
            tofile=f"{cfg['bundle_dir']}/scripts/finetune_pilot.py",
            lineterm="", n=2)),
    }
    record["declared_deltas"]["BUNDLE_MARKER.json"] = {
        "scope": f"MARKER ONLY - bundle {cfg['marker_bundle']}, campaign "
                 "Stage F follow-up M1 pilot, same checkpoint_sha256, "
                 f"m1_lambda={lam_literal}",
    }
    if "dataset-metadata.json" in changed:
        record["declared_deltas"]["dataset-metadata.json"] = {
            "scope": "UPLOAD-TIME ONLY - stale copy removed"
                     + (" (was already absent)" if stale_missing else "")
                     + "; push_f1.py dataset regenerates it",
        }

    # Init checkpoint must still match the frozen hash after copying.
    ck = BUNDLE / "checkpoints" / "armp_stage1_best.pth"
    ck_sha = sha256(ck)
    record["init_checkpoint"] = {
        "path": "checkpoints/armp_stage1_best.pth",
        "sha256": ck_sha, "expected": STAGE1_SHA,
        "match": ck_sha == STAGE1_SHA}
    ok = verdict_ok and ck_sha == STAGE1_SHA
    record["changed_files"] = sorted(changed)
    record["unexpected_diffs"] = sorted(unexpected)
    record["verdict"] = "PASS" if ok else "FAIL"
    (HERE / cfg["integrity"]).write_text(
        json.dumps(record, indent=2))
    # The kernel re-verifies hashes on Kaggle, so the manifest ships inside
    # the bundle too (this copy is identical at build time by construction).
    (BUNDLE / cfg["integrity"]).write_text(
        json.dumps(record, indent=2))

    n_ident = sum(1 for v in record["files"].values() if v["identical"])
    print(f"byte-identical files: {n_ident}/{len(record['files'])}")
    print(f"changed files:        {sorted(changed)}")
    print(f"init checkpoint:      {'MATCH' if record['init_checkpoint']['match'] else 'MISMATCH'}")
    print(f"verdict:              {record['verdict']}")
    if not ok:
        if unexpected:
            print(f"UNEXPECTED DIFFS: {sorted(unexpected)}")
        if missing_required:
            print(f"MISSING REQUIRED DIFFS: {sorted(missing_required)}")
        sys.exit(1)


if __name__ == "__main__":
    main(parse_args())
