#!/usr/bin/env python
"""Assemble the Stage-F capacity-twin Kaggle bundle and record its integrity.

Copies `stage_e_recipe/kaggle/bundle/` (the frozen E0 bundle) to
`stage_f/followup/kaggle/bundle_twin/`, applies the width-48 twin edits, adds
the frozen twin init checkpoint, rewrites `BUNDLE_MARKER.json`, and writes
`stage_f/followup/kaggle/source_integrity_twin.json` listing every file with
its sha256 and whether it is byte-identical to the E0 bundle.

Twin edits (and NOTHING else):
- `checkpoints/twin48_init.pth` ADDED: copy of
  `stage_f/followup/twin/twin48_init.pth` (A2-finalized; sha read from
  `stage_f/followup/twin/preflight_a2.json`, verdict must be A2_PASS).
- `scripts/finetune_pilot.py`: ARM_V_CONFIG gains `feature_channels=48`;
  ARM_V_PARAMS 397954 -> 891074; `integrity_guard` compares keys/shapes
  against the bundle's `checkpoints/twin48_init.pth` (the 48-channel
  reference) instead of `phase1/runs/arm_v/arm_v_best.pth` (the 32-channel
  reference, which the twin can never match shape-for-shape).
- `scripts/run_arm.py`: EXPECTED_PARAMS 397954 -> 891074;
  EXPECTED_SHA_ARMP_STAGE1 (armp sha) -> EXPECTED_SHA_TWIN48_INIT (twin sha).
- `scripts/eval_tier2.py`: CFG gains `feature_channels=48`; EXPECTED_PARAMS
  397954 -> 891074 (kernel scoring builds the model from this CFG).
- `BUNDLE_MARKER.json`: marker `stage-f-twin48`.
- `dataset-metadata.json`: stale copy removed (regenerated by
  `push_twin.py dataset` at upload time, exactly as push_f1.py does).

Verdict PASS only if the differing set is exactly the six files above
(`dataset-metadata.json` removal counts as a difference; the manifest's own
inside-bundle copy is written AFTER the walk, exactly as build_bundle_f1m.py
does, so it is not part of the compared set).

Not a training run and not a Kaggle upload: this only writes `bundle_twin/`
and `source_integrity_twin.json`.

    python stage_f/followup/kaggle/build_bundle_twin.py
"""
from __future__ import annotations

import difflib
import hashlib
import json
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
E0_BUNDLE = REPO / "stage_e_recipe" / "kaggle" / "bundle"
BUNDLE = HERE / "bundle_twin"
INTEGRITY = HERE / "source_integrity_twin.json"
TWIN_INIT = REPO / "stage_f" / "followup" / "twin" / "twin48_init.pth"
PREFLIGHT_A2 = REPO / "stage_f" / "followup" / "twin" / "preflight_a2.json"

TWIN_PARAMS = 891074
OLD_PARAMS = 397954
ARMP_SHA = "3ae6fb3be6b2bda9287b325ccbe6d1397744c8f20ef5e56c046176d9f1a29be7"

# Files allowed to differ from the E0 bundle (or be absent/added).
REQUIRED_DIFF = {"BUNDLE_MARKER.json",
                 "checkpoints/twin48_init.pth",
                 "scripts/finetune_pilot.py",
                 "scripts/run_arm.py",
                 "scripts/eval_tier2.py"}
OPTIONAL_DIFF = {"dataset-metadata.json"}


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def replace_once(text: str, old: str, new: str, why: str) -> str:
    if old not in text:
        raise SystemExit(f"TWIN BUILD FAIL: target not found -> {why}\n{old[:120]!r}")
    if text.count(old) != 1:
        raise SystemExit(
            f"TWIN BUILD FAIL: target appears {text.count(old)}x -> {why}\n{old[:120]!r}")
    return text.replace(old, new, 1)


def main() -> None:
    if not E0_BUNDLE.is_dir():
        sys.exit(f"TWIN BUILD FAIL: E0 bundle not found: {E0_BUNDLE}")
    if not PREFLIGHT_A2.is_file():
        sys.exit(f"TWIN BUILD FAIL: {PREFLIGHT_A2} missing (run finalize_twin_init.py first)")
    pre = json.loads(PREFLIGHT_A2.read_text(encoding="utf-8"))
    if pre.get("verdict") != "A2_PASS":
        sys.exit(f"TWIN BUILD FAIL: preflight_a2 verdict is {pre.get('verdict')!r}, not A2_PASS")
    twin_sha = pre["twin_init"]["sha256"]
    if not twin_sha or not TWIN_INIT.is_file() or sha256(TWIN_INIT) != twin_sha:
        sys.exit("TWIN BUILD FAIL: twin48_init.pth missing or sha mismatch vs preflight_a2.json")
    if pre.get("param_count") != TWIN_PARAMS:
        sys.exit(f"TWIN BUILD FAIL: param_count {pre.get('param_count')} != {TWIN_PARAMS}")

    if BUNDLE.exists():
        shutil.rmtree(BUNDLE)
    shutil.copytree(E0_BUNDLE, BUNDLE)

    # The one new artefact: the A2-finalized twin init checkpoint.
    shutil.copy2(TWIN_INIT, BUNDLE / "checkpoints" / "twin48_init.pth")

    # Stale upload-time metadata is removed; push_twin.py writes it fresh.
    stale = BUNDLE / "dataset-metadata.json"
    stale_missing = not stale.exists()
    if stale.exists():
        stale.unlink()

    # --- scripts/finetune_pilot.py: width + guard ---
    fp = BUNDLE / "scripts" / "finetune_pilot.py"
    original_fp = fp.read_text(encoding="utf-8")
    patched = original_fp
    patched = replace_once(
        patched,
        "ARM_V_CONFIG = dict(downsample_levels=3, num_disparities=24,\n"
        "                    cost_volume_shift=\"right\", regression_normalize=True)",
        "ARM_V_CONFIG = dict(downsample_levels=3, num_disparities=24,\n"
        "                    cost_volume_shift=\"right\", regression_normalize=True,\n"
        "                    feature_channels=48)",
        "twin width knob: model config builds the 48-channel twin")
    patched = replace_once(
        patched,
        f"ARM_V_PARAMS = {OLD_PARAMS}",
        f"ARM_V_PARAMS = {TWIN_PARAMS}",
        "twin param count")
    patched = replace_once(
        patched,
        "    ref_blob = torch.load(REPO_ROOT / \"phase1\" / \"runs\" / \"arm_v\" / \"arm_v_best.pth\",\n"
        "                          map_location=\"cpu\", weights_only=False)\n"
        "    ref_keys = sorted(ref_blob[\"model\"].keys())",
        "    ref_blob = torch.load(REPO_ROOT / \"checkpoints\" / \"twin48_init.pth\",\n"
        "                          map_location=\"cpu\", weights_only=False)\n"
        "    ref_state = ref_blob[\"model\"] if isinstance(ref_blob, dict) and \"model\" in ref_blob else ref_blob\n"
        "    ref_keys = sorted(ref_state.keys())",
        "twin guard reference: 48-channel twin init, not the 32-channel arm_v ref")
    patched = replace_once(
        patched,
        "    shapes_ok = all(tuple(model.state_dict()[k].shape) == tuple(ref_blob[\"model\"][k].shape)\n"
        "                    for k in keys) if keys == ref_keys else False",
        "    shapes_ok = all(tuple(model.state_dict()[k].shape) == tuple(ref_state[k].shape)\n"
        "                    for k in keys) if keys == ref_keys else False",
        "twin guard shapes: compare against the twin reference state")
    fp.write_text(patched, encoding="utf-8", newline="")

    # --- scripts/run_arm.py: post-hoc param + init-sha gates ---
    rp = BUNDLE / "scripts" / "run_arm.py"
    original_rp = rp.read_text(encoding="utf-8")
    patched_rp = original_rp
    patched_rp = replace_once(
        patched_rp,
        "  failure | wrong-checkpoint resume | wall > timeout | projected wall > timeout.\n\"\"\"",
        "  failure | wrong-checkpoint resume | wall > timeout | projected wall > timeout.\n"
        "Twin bundle: EXPECTED_PARAMS is the 48-channel count and the init sha\n"
        "is the A2-finalized twin48 init (not the ARM-P Stage-1 sha).\n\"\"\"",
        "twin run_arm docstring note")
    patched_rp = replace_once(
        patched_rp,
        f"EXPECTED_PARAMS = {OLD_PARAMS}",
        f"EXPECTED_PARAMS = {TWIN_PARAMS}",
        "twin run_arm param gate")
    patched_rp = replace_once(
        patched_rp,
        f"EXPECTED_SHA_ARMP_STAGE1 = \"{ARMP_SHA}\"",
        f"EXPECTED_SHA_TWIN48_INIT = \"{twin_sha}\"",
        "twin run_arm init-sha gate")
    patched_rp = patched_rp.replace(
        "EXPECTED_SHA_ARMP_STAGE1", "EXPECTED_SHA_TWIN48_INIT")
    if "EXPECTED_SHA_ARMP_STAGE1" in patched_rp:
        raise SystemExit("TWIN BUILD FAIL: stale EXPECTED_SHA_ARMP_STAGE1 reference left in run_arm.py")
    patched_rp = replace_once(
        patched_rp,
        "  NaN/Inf loss | zero valid pixels | param count != 397954 | strict-load",
        "  NaN/Inf loss | zero valid pixels | param count != 891074 | strict-load",
        "twin run_arm STOP docstring count")
    rp.write_text(patched_rp, encoding="utf-8", newline="")

    # --- scripts/eval_tier2.py: scoring model width + params ---
    ep = BUNDLE / "scripts" / "eval_tier2.py"
    original_ep = ep.read_text(encoding="utf-8")
    patched_ep = original_ep
    patched_ep = replace_once(
        patched_ep,
        "CFG = dict(downsample_levels=3, num_disparities=24, cost_volume_shift=\"right\",\n"
        "           regression_normalize=True)",
        "CFG = dict(downsample_levels=3, num_disparities=24, cost_volume_shift=\"right\",\n"
        "           regression_normalize=True, feature_channels=48)",
        "twin scoring model: 48-channel config")
    patched_ep = replace_once(
        patched_ep,
        f"EXPECTED_PARAMS = {OLD_PARAMS}",
        f"EXPECTED_PARAMS = {TWIN_PARAMS}",
        "twin scoring param gate")
    ep.write_text(patched_ep, encoding="utf-8", newline="")

    # Rewrite the marker.
    marker = {
        "bundle": "stage-f-twin48",
        "campaign": "Stage F follow-up capacity-twin pilot",
        "experiment": "t48",
        "initialization": "width-48 function-preserving embed of ARM-P Stage-1 (amendment A2)",
        "checkpoint": "checkpoints/twin48_init.pth",
        "checkpoint_sha256": twin_sha,
        "source_stage1_sha256": ARMP_SHA,
        "feature_channels": 48,
        "param_count": TWIN_PARAMS,
        "recipe_source": "stage_b_armp/20260919T012646Z_tier2_seed1/scripts",
        "amendment": "docs/superpowers/specs/2026-09-25-stage-f-followup-amendment-A2.md",
        "patched": ["scripts/finetune_pilot.py (width 48 + twin guard)",
                    "scripts/run_arm.py (twin params + twin init sha)",
                    "scripts/eval_tier2.py (twin scoring width + params)"],
        "training_authorized": False,
    }
    (BUNDLE / "BUNDLE_MARKER.json").write_text(json.dumps(marker, indent=2))

    # Integrity: every file hashed, compared against the E0 bundle.
    record: dict = {
        "bundle": "stage_f/followup/kaggle/bundle_twin",
        "purpose": "Stage F follow-up capacity-twin (width-48) Kaggle T4 execution bundle",
        "source_bundle": "stage_e_recipe/kaggle/bundle (frozen E0)",
        "twin_init_sha256": twin_sha,
        "twin_param_count": TWIN_PARAMS,
        "files": {},
        "declared_deltas": {},
        "verdict": None,
    }
    e0_files = {p.relative_to(E0_BUNDLE).as_posix()
                for p in E0_BUNDLE.rglob("*") if p.is_file()}
    twin_files = {p.relative_to(BUNDLE).as_posix()
                  for p in BUNDLE.rglob("*") if p.is_file()}
    for rel in sorted(e0_files | twin_files):
        e0_p, tw_p = E0_BUNDLE / rel, BUNDLE / rel
        if e0_p.is_file() and tw_p.is_file():
            h0, h1 = sha256(e0_p), sha256(tw_p)
            record["files"][rel] = {"sha256": h1, "e0_sha256": h0,
                                    "identical": h0 == h1}
        elif tw_p.is_file():
            record["files"][rel] = {"sha256": sha256(tw_p),
                                    "e0_sha256": None, "identical": False,
                                    "note": "added (not in E0 bundle)"}
        else:
            record["files"][rel] = {"sha256": None,
                                    "e0_sha256": sha256(e0_p),
                                    "identical": False,
                                    "note": "removed from E0 bundle copy"}
    changed = {rel for rel, v in record["files"].items() if not v["identical"]}
    unexpected = changed - REQUIRED_DIFF - OPTIONAL_DIFF
    missing_required = REQUIRED_DIFF - changed
    record["declared_deltas"]["checkpoints/twin48_init.pth"] = {
        "scope": "ADDED INIT ONLY - A2-finalized width-48 embed "
                 f"(sha {twin_sha[:12]}..., {TWIN_PARAMS} params); "
                 "the ARM-P Stage-1 checkpoint stays byte-identical alongside",
    }
    record["declared_deltas"]["scripts/finetune_pilot.py"] = {
        "scope": "TWIN WIDTH + GUARD ONLY - ARM_V_CONFIG gains feature_channels=48; "
                 f"ARM_V_PARAMS {OLD_PARAMS}->{TWIN_PARAMS}; integrity_guard reference "
                 "is the bundle twin48_init (48-channel shapes) instead of arm_v_best "
                 "(32-channel shapes, unmatchable by construction); optimizer, scheduler, "
                 "data, aug, loss, validation, checkpointing, init path, seed, "
                 "determinism unchanged",
        "unified_diff": list(difflib.unified_diff(
            original_fp.splitlines(), patched.splitlines(),
            fromfile="bundle/scripts/finetune_pilot.py",
            tofile="bundle_twin/scripts/finetune_pilot.py",
            lineterm="", n=2)),
    }
    record["declared_deltas"]["scripts/run_arm.py"] = {
        "scope": f"TWIN GATES ONLY - EXPECTED_PARAMS {OLD_PARAMS}->{TWIN_PARAMS}; "
                 "init-sha gate is the twin48 sha (renamed EXPECTED_SHA_TWIN48_INIT); "
                 "STOP/complete logic otherwise unchanged",
        "unified_diff": list(difflib.unified_diff(
            original_rp.splitlines(), patched_rp.splitlines(),
            fromfile="bundle/scripts/run_arm.py",
            tofile="bundle_twin/scripts/run_arm.py",
            lineterm="", n=2)),
    }
    record["declared_deltas"]["scripts/eval_tier2.py"] = {
        "scope": "TWIN SCORING ONLY - CFG gains feature_channels=48 so the kernel "
                 f"scoring model matches the trained twin; EXPECTED_PARAMS "
                 f"{OLD_PARAMS}->{TWIN_PARAMS}; metrics/contract code unchanged",
        "unified_diff": list(difflib.unified_diff(
            original_ep.splitlines(), patched_ep.splitlines(),
            fromfile="bundle/scripts/eval_tier2.py",
            tofile="bundle_twin/scripts/eval_tier2.py",
            lineterm="", n=2)),
    }
    record["declared_deltas"]["BUNDLE_MARKER.json"] = {
        "scope": "MARKER ONLY - bundle stage-f-twin48, twin checkpoint sha, "
                 "feature_channels 48, param_count 891074",
    }
    if "dataset-metadata.json" in changed:
        record["declared_deltas"]["dataset-metadata.json"] = {
            "scope": "UPLOAD-TIME ONLY - stale copy removed"
                     + (" (was already absent)" if stale_missing else "")
                     + "; push_twin.py dataset regenerates it",
        }

    ck_armp = BUNDLE / "checkpoints" / "armp_stage1_best.pth"
    ck_armp_sha = sha256(ck_armp)
    ck_twin = BUNDLE / "checkpoints" / "twin48_init.pth"
    ck_twin_sha = sha256(ck_twin)
    record["init_checkpoints"] = {
        "armp_stage1_best.pth": {"sha256": ck_armp_sha, "expected": ARMP_SHA,
                                 "match": ck_armp_sha == ARMP_SHA},
        "twin48_init.pth": {"sha256": ck_twin_sha, "expected": twin_sha,
                            "match": ck_twin_sha == twin_sha},
    }
    ok = (not unexpected and not missing_required
          and ck_armp_sha == ARMP_SHA and ck_twin_sha == twin_sha)
    record["changed_files"] = sorted(changed)
    record["unexpected_diffs"] = sorted(unexpected)
    record["verdict"] = "PASS" if ok else "FAIL"
    INTEGRITY.write_text(json.dumps(record, indent=2))
    # The kernel re-verifies hashes on Kaggle, so the manifest ships inside
    # the bundle too (written AFTER the walk, so it is not in changed_files —
    # same convention as build_bundle_f1m.py).
    (BUNDLE / INTEGRITY.name).write_text(json.dumps(record, indent=2))

    n_ident = sum(1 for v in record["files"].values() if v["identical"])
    print(f"byte-identical files: {n_ident}/{len(record['files'])}")
    print(f"changed files:        {sorted(changed)}")
    print(f"armp checkpoint:      {'MATCH' if ck_armp_sha == ARMP_SHA else 'MISMATCH'}")
    print(f"twin checkpoint:      {'MATCH' if ck_twin_sha == twin_sha else 'MISMATCH'}")
    print(f"verdict:              {record['verdict']}")
    if not ok:
        if unexpected:
            print(f"UNEXPECTED DIFFS: {sorted(unexpected)}")
        if missing_required:
            print(f"MISSING REQUIRED DIFFS: {sorted(missing_required)}")
        sys.exit(1)


if __name__ == "__main__":
    main()
