#!/usr/bin/env python
"""Assemble the Stage-F L1-continuation Kaggle bundles and record integrity.

Copies `stage_e_recipe/kaggle/bundle/` (the frozen E0 bundle) twice — to
`stage_f/followup/kaggle/bundle_l1c/` (Smooth-L1 control) and
`stage_f/followup/kaggle/bundle_l1m/` (masked-L1 arm) — applies the frozen
§8 continuation edits, and writes `source_integrity_l1c.json` /
`source_integrity_l1m.json` listing every file with its sha256 and whether
it is byte-identical to the E0 bundle.

Why two bundles (not one bundle with an arm switch): the loss is the single
frozen knob and each Kaggle kernel mounts exactly one bundle, so an arm can
never run the other arm's loss by a mis-set flag. Same convention as the F1
pilot (bundle_f1m/ + bundle_f1m10/ + unchanged-E0 control); here BOTH arms
need their own bundle because the continuation recipe itself (init/lr/epochs)
differs from E0, so there is no unchanged-E0 control to reuse.

Common continuation edits (BOTH bundles, and NOTHING else):
- `checkpoints/e3_seed0_final.pth` ADDED: copy of
  `stage_e_recipe/kaggle/e3_output/seed0/e3_seed0_final.pth` (sha
  82e58bc441a4382ec449479fe26bf479f6b45e9ace4d79b530abeeb40ea79c6d).
  The ARM-P Stage-1 checkpoint stays byte-identical alongside.
- `scripts/finetune_pilot.py`: `LR = 1e-3` -> `LR = 1e-4` (FRESH Adam, §8);
  `SCHEDULER` "... over 200 epochs" -> "... over 40 epochs" (T_max follows
  EPOCHS, which the kernel sets to 40 via --epochs; the env default "200"
  becomes "40" so a bare run still matches the continuation recipe).
- `scripts/run_arm.py`: init-sha gate `EXPECTED_SHA_ARMP_STAGE1` (armp sha)
  -> `EXPECTED_SHA_E3_SEED0_FINAL` (e3 seed0 final sha); epoch-count guards
  200 -> 40 (`--epochs` default, `len(rows)`, `epochs_run`,
  `epochs_completed`, projected-wall scale); a docstring note records the
  40-epoch continuation. Param count 397954 UNCHANGED (same architecture).
- `scripts/eval_tier2.py`: UNCHANGED (same 32-channel config, same params).
- `BUNDLE_MARKER.json`: rewritten per arm.
- `dataset-metadata.json`: stale copy removed (regenerated by `push_l1.py
  dataset` at upload time, exactly as push_f1.py does).

l1m-only edits (the single frozen knob):
- `scripts/finetune_pilot.py`: `import torch.nn.functional as F`, a
  bundle-local `masked_l1` (SAME valid mask as masked_smooth_l1 —
  target > 0 and target < max_disparity — plain L1 instead of Smooth-L1;
  repo src/ is NEVER edited), the training-step call
  `masked_smooth_l1(...)` -> `masked_l1(...)`, and the exp_config "loss"
  record string. Optimizer (fresh Adam 1e-4), scheduler, data, aug, batch 2,
  crop, seed, determinism, init path, epochs UNCHANGED.

Verdict PASS only if, per bundle, the differing set vs E0 is exactly the
files above, the E3 init sha matches, AND bundle_l1c vs bundle_l1m differ
ONLY in scripts/finetune_pilot.py + BUNDLE_MARKER.json (excluding the
self-describing inside-bundle integrity manifests, which necessarily embed
per-arm names).

Not a training run and not a Kaggle upload: this only writes bundle_l1c/,
bundle_l1m/ and the two source_integrity_l1*.json files.

    python stage_f/followup/kaggle/build_bundle_l1.py
"""
from __future__ import annotations

import difflib
import hashlib
import json
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
E0_BUNDLE = REPO / "stage_e_recipe" / "kaggle" / "bundle"
E3_FINAL = REPO / "stage_e_recipe" / "kaggle" / "e3_output" / "seed0" / "e3_seed0_final.pth"

E3_SHA = "82e58bc441a4382ec449479fe26bf479f6b45e9ace4d79b530abeeb40ea79c6d"
ARMP_SHA = "3ae6fb3be6b2bda9287b325ccbe6d1397744c8f20ef5e56c046176d9f1a29be7"
PARAMS = 397954
EPOCHS = 40

ARM_CONFIG = {
    "l1c": {"bundle_dir": "bundle_l1c",
            "integrity": "source_integrity_l1c.json",
            "marker_bundle": "stage-f-l1c",
            "experiment": "l1c",
            "bundle_rel": "stage_f/followup/kaggle/bundle_l1c",
            "title": "Stage F L1C bundle",
            "loss_desc": "Smooth-L1 control (the E0 loss, unchanged)",
            "init_desc": "E3 seed0 final (continuation)"},
    "l1m": {"bundle_dir": "bundle_l1m",
            "integrity": "source_integrity_l1m.json",
            "marker_bundle": "stage-f-l1m",
            "experiment": "l1m",
            "bundle_rel": "stage_f/followup/kaggle/bundle_l1m",
            "title": "Stage F L1M bundle",
            "loss_desc": "masked L1 (same valid mask/max-disparity, plain L1 "
                         "instead of Smooth-L1)",
            "init_desc": "E3 seed0 final (continuation)"},
}

# Files allowed to differ from the E0 bundle (or be absent/added).
REQUIRED_DIFF = {"BUNDLE_MARKER.json",
                 "checkpoints/e3_seed0_final.pth",
                 "scripts/finetune_pilot.py",
                 "scripts/run_arm.py"}
OPTIONAL_DIFF = {"dataset-metadata.json"}

MASKED_L1_DEF = '''

def masked_l1(
    prediction: torch.Tensor,
    target: torch.Tensor,
    max_disparity: float | None = None,
) -> tuple[torch.Tensor, int]:
    """Plain masked L1 (mean absolute error) over valid GT pixels only.

    L1-pilot intervention, bundle-local only (repo src/ untouched): the SAME
    valid mask as masked_smooth_l1 (target > 0 and target < max_disparity)
    with a plain L1 instead of Smooth-L1. Returns (loss, valid_pixel_count).
    """
    valid = target > 0
    if max_disparity is not None:
        valid = valid & (target < max_disparity)
    count = int(valid.sum())
    if count == 0:
        return (prediction.sum() * 0.0), 0
    return F.l1_loss(prediction[valid], target[valid]), count
'''


def sha256(p: Path) -> str:
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def replace_once(text: str, old: str, new: str, why: str) -> str:
    if old not in text:
        raise SystemExit(f"L1 BUILD FAIL: target not found -> {why}\n{old[:120]!r}")
    if text.count(old) != 1:
        raise SystemExit(
            f"L1 BUILD FAIL: target appears {text.count(old)}x -> {why}\n{old[:120]!r}")
    return text.replace(old, new, 1)


def patch_finetune_common(text: str) -> str:
    text = replace_once(
        text,
        'EPOCHS = int(os.environ.get("P2A_EPOCHS", "200"))',
        'EPOCHS = int(os.environ.get("P2A_EPOCHS", "40"))',
        "L1 continuation: 40-epoch default (kernel sets P2A_EPOCHS=40 via --epochs)")
    text = replace_once(
        text,
        "LR = 1e-3",
        "LR = 1e-4",
        "L1 continuation: FRESH Adam lr 1e-4 (§8)")
    text = replace_once(
        text,
        'SCHEDULER = "cosine annealing to 0 over 200 epochs"',
        'SCHEDULER = "cosine annealing to 0 over 40 epochs"',
        "L1 continuation: cosine T_max follows EPOCHS (=40 on the kernel)")
    return text


def patch_finetune_l1m(text: str) -> str:
    text = replace_once(
        text,
        "import torch\nfrom torch.utils.data import DataLoader, Dataset\n",
        "import torch\nimport torch.nn.functional as F\n"
        "from torch.utils.data import DataLoader, Dataset\n",
        "l1m loss needs torch.nn.functional (F.l1_loss); nothing else uses it")
    text = replace_once(
        text,
        "from src.models.stereonet import StereoNet, StereoNetConfig  # noqa: E402\n",
        "from src.models.stereonet import StereoNet, StereoNetConfig  # noqa: E402\n"
        + MASKED_L1_DEF,
        "l1m loss: bundle-local masked_l1 (same mask, plain L1); repo src/ untouched")
    text = replace_once(
        text,
        "            out = model(left, right)\n"
        "            loss, n = masked_smooth_l1(out, disparity, max_disparity=float(config.max_disparity_px))\n",
        "            out = model(left, right)\n"
        "            loss, n = masked_l1(out, disparity, max_disparity=float(config.max_disparity_px))\n",
        "l1m single knob: training-step loss call (mask rule identical)")
    text = replace_once(
        text,
        '"loss": "masked smooth L1, beta=1.0, valid = gt > 0 and gt < max_disparity",',
        '"loss": "masked L1 (mean absolute error), valid = gt > 0 and gt < max_disparity '
        '(same mask/max-disparity; plain L1 instead of Smooth-L1)",',
        "l1m record string: honest loss description in exp_config")
    return text


def patch_run_arm(text: str) -> str:
    text = replace_once(
        text,
        "  failure | wrong-checkpoint resume | wall > timeout | projected wall > timeout.\n\"\"\"",
        "  failure | wrong-checkpoint resume | wall > timeout | projected wall > timeout.\n"
        "L1 bundle: EXPECTED_PARAMS stays 397954 (same architecture); the init sha\n"
        "is the E3 seed0 FINAL (40-epoch continuation, §8), not ARM-P Stage-1;\n"
        "epoch-count guards are 40, not 200.\n\"\"\"",
        "l1 run_arm docstring note")
    text = replace_once(
        text,
        f'EXPECTED_SHA_ARMP_STAGE1 = "{ARMP_SHA}"',
        f'EXPECTED_SHA_E3_SEED0_FINAL = "{E3_SHA}"',
        "l1 run_arm init-sha gate: E3 seed0 final")
    text = text.replace("EXPECTED_SHA_ARMP_STAGE1", "EXPECTED_SHA_E3_SEED0_FINAL")
    if "EXPECTED_SHA_ARMP_STAGE1" in text:
        raise SystemExit("L1 BUILD FAIL: stale EXPECTED_SHA_ARMP_STAGE1 reference left in run_arm.py")
    text = replace_once(
        text,
        '    ap.add_argument("--epochs", type=int, default=200,\n'
        '                    help="STAGE E: P2A_EPOCHS; 200 = frozen recipe, 400 = E3")',
        '    ap.add_argument("--epochs", type=int, default=40,\n'
        '                    help="L1 continuation (§8): P2A_EPOCHS; 40 = frozen L1 recipe")',
        "l1 run_arm --epochs default 40")
    text = replace_once(
        text,
        "    if len(rows) != 200:",
        "    if len(rows) != 40:",
        "l1 run_arm post-hoc epoch count 40")
    text = replace_once(
        text,
        '    if rec.get("epochs_run") != 200:',
        '    if rec.get("epochs_run") != 40:',
        "l1 run_arm record epoch count 40")
    text = replace_once(
        text,
        '              "epochs_completed": 200, "training_duration_s": wall_s,',
        '              "epochs_completed": 40, "training_duration_s": wall_s,',
        "l1 run_arm record epochs_completed 40")
    text = replace_once(
        text,
        "                    proj = (now - arm_start) / done * 200.0",
        "                    proj = (now - arm_start) / done * 40.0",
        "l1 run_arm projected-wall scale 40")
    return text


def build_arm(arm: str) -> dict:
    cfg = ARM_CONFIG[arm]
    BUNDLE = HERE / cfg["bundle_dir"]
    INTEGRITY = HERE / cfg["integrity"]
    if not E0_BUNDLE.is_dir():
        sys.exit(f"L1 BUILD FAIL: E0 bundle not found: {E0_BUNDLE}")
    if not E3_FINAL.is_file() or sha256(E3_FINAL) != E3_SHA:
        sys.exit("L1 BUILD FAIL: e3_seed0_final.pth missing or sha mismatch "
                 f"(expected {E3_SHA[:12]}...)")

    if BUNDLE.exists():
        shutil.rmtree(BUNDLE)
    shutil.copytree(E0_BUNDLE, BUNDLE)

    # The one new artefact: the E3 seed0 FINAL continuation init.
    shutil.copy2(E3_FINAL, BUNDLE / "checkpoints" / "e3_seed0_final.pth")

    # Stale upload-time metadata is removed; push_l1.py writes it fresh.
    stale = BUNDLE / "dataset-metadata.json"
    stale_missing = not stale.exists()
    if stale.exists():
        stale.unlink()

    # --- scripts/finetune_pilot.py: continuation recipe (+ l1m loss knob) ---
    fp = BUNDLE / "scripts" / "finetune_pilot.py"
    original_fp = fp.read_text(encoding="utf-8")
    patched = patch_finetune_common(original_fp)
    if arm == "l1m":
        patched = patch_finetune_l1m(patched)
    fp.write_text(patched, encoding="utf-8", newline="")

    # --- scripts/run_arm.py: init-sha + epoch-count gates ---
    rp = BUNDLE / "scripts" / "run_arm.py"
    original_rp = rp.read_text(encoding="utf-8")
    patched_rp = patch_run_arm(original_rp)
    rp.write_text(patched_rp, encoding="utf-8", newline="")

    # Rewrite the marker.
    marker = {
        "bundle": cfg["marker_bundle"],
        "campaign": "Stage F follow-up L1 continuation pilot (§8)",
        "experiment": cfg["experiment"],
        "initialization": cfg["init_desc"],
        "checkpoint": "checkpoints/e3_seed0_final.pth",
        "checkpoint_sha256": E3_SHA,
        "loss": cfg["loss_desc"],
        "optimizer": "fresh Adam lr 1e-4 (not a resumed optimizer)",
        "schedule": "cosine annealing to 0 over 40 epochs (T_max=EPOCHS=40)",
        "epochs": EPOCHS,
        "seed": 0,
        "recipe_source": "stage_b_armp/20260919T012646Z_tier2_seed1/scripts",
        "design": "docs/superpowers/specs/2026-09-24-stage-f-followup-design.md §8",
        "patched": ["scripts/finetune_pilot.py (L1 continuation: lr 1e-4, 40 epochs"
                    + (", masked_l1 loss knob" if arm == "l1m" else ", E0 loss unchanged") + ")",
                    "scripts/run_arm.py (E3-final init sha, 40-epoch guards)"],
        "training_authorized": False,
    }
    (BUNDLE / "BUNDLE_MARKER.json").write_text(json.dumps(marker, indent=2))

    # Integrity: every file hashed, compared against the E0 bundle.
    record: dict = {
        "bundle": cfg["bundle_rel"],
        "purpose": f"Stage F follow-up L1 continuation {arm} Kaggle T4 execution bundle (§8)",
        "source_bundle": "stage_e_recipe/kaggle/bundle (frozen E0)",
        "init_checkpoint": {"path": "checkpoints/e3_seed0_final.pth",
                            "sha256": E3_SHA},
        "loss": cfg["loss_desc"],
        "files": {},
        "declared_deltas": {},
        "verdict": None,
    }
    e0_files = {p.relative_to(E0_BUNDLE).as_posix()
                for p in E0_BUNDLE.rglob("*") if p.is_file()}
    arm_files = {p.relative_to(BUNDLE).as_posix()
                 for p in BUNDLE.rglob("*") if p.is_file()}
    for rel in sorted(e0_files | arm_files):
        e0_p, arm_p = E0_BUNDLE / rel, BUNDLE / rel
        if e0_p.is_file() and arm_p.is_file():
            h0, h1 = sha256(e0_p), sha256(arm_p)
            record["files"][rel] = {"sha256": h1, "e0_sha256": h0,
                                    "identical": h0 == h1}
        elif arm_p.is_file():
            record["files"][rel] = {"sha256": sha256(arm_p),
                                    "e0_sha256": None, "identical": False,
                                    "note": "added (not in E0 bundle)"}
        else:
            record["files"][rel] = {"sha256": None,
                                    "e0_sha256": sha256(e0_p),
                                    "identical": False,
                                    "note": "removed from E0 bundle copy"}
    changed = {rel for rel, v in record["files"].items() if not v["identical"]}
    unexpected = changed - REQUIRED_DIFF - OPTIONAL_DIFF
    missing_required = REQUIRED_DIFF - changed
    record["declared_deltas"]["checkpoints/e3_seed0_final.pth"] = {
        "scope": "ADDED INIT ONLY - E3 seed0 final continuation init "
                 f"(sha {E3_SHA[:12]}..., {PARAMS} params, same architecture); "
                 "the ARM-P Stage-1 checkpoint stays byte-identical alongside",
    }
    record["declared_deltas"]["scripts/finetune_pilot.py"] = {
        "scope": "L1 CONTINUATION ONLY - LR 1e-3->1e-4 (fresh Adam), 200->40 "
                 "epochs (default + schedule string; T_max follows EPOCHS) "
                 + ("+ the single loss knob (F import, bundle-local masked_l1, "
                    "one call line, record string); data, aug, batch, crop, "
                    "seed, determinism, init path, validation, checkpointing "
                    "unchanged" if arm == "l1m" else
                    "; E0 Smooth-L1 loss byte-identical; data, aug, batch, "
                    "crop, seed, determinism, init path, validation, "
                    "checkpointing unchanged"),
        "unified_diff": list(difflib.unified_diff(
            original_fp.splitlines(), patched.splitlines(),
            fromfile="bundle/scripts/finetune_pilot.py",
            tofile=f"{cfg['bundle_dir']}/scripts/finetune_pilot.py",
            lineterm="", n=2)),
    }
    record["declared_deltas"]["scripts/run_arm.py"] = {
        "scope": "L1 GATES ONLY - init-sha gate is the E3 seed0 final sha "
                 "(renamed EXPECTED_SHA_E3_SEED0_FINAL); epoch-count guards "
                 "200->40; EXPECTED_PARAMS 397954 UNCHANGED; STOP/complete "
                 "logic otherwise unchanged",
        "unified_diff": list(difflib.unified_diff(
            original_rp.splitlines(), patched_rp.splitlines(),
            fromfile="bundle/scripts/run_arm.py",
            tofile=f"{cfg['bundle_dir']}/scripts/run_arm.py",
            lineterm="", n=2)),
    }
    record["declared_deltas"]["BUNDLE_MARKER.json"] = {
        "scope": f"MARKER ONLY - bundle {cfg['marker_bundle']}, E3-final init "
                 f"sha, {cfg['loss_desc']}",
    }
    if "dataset-metadata.json" in changed:
        record["declared_deltas"]["dataset-metadata.json"] = {
            "scope": "UPLOAD-TIME ONLY - stale copy removed"
                     + (" (was already absent)" if stale_missing else "")
                     + "; push_l1.py dataset regenerates it",
        }

    ck_armp = BUNDLE / "checkpoints" / "armp_stage1_best.pth"
    ck_armp_sha = sha256(ck_armp)
    ck_e3 = BUNDLE / "checkpoints" / "e3_seed0_final.pth"
    ck_e3_sha = sha256(ck_e3)
    record["init_checkpoints"] = {
        "armp_stage1_best.pth": {"sha256": ck_armp_sha, "expected": ARMP_SHA,
                                 "match": ck_armp_sha == ARMP_SHA},
        "e3_seed0_final.pth": {"sha256": ck_e3_sha, "expected": E3_SHA,
                               "match": ck_e3_sha == E3_SHA},
    }
    ok = (not unexpected and not missing_required
          and ck_armp_sha == ARMP_SHA and ck_e3_sha == E3_SHA)
    record["changed_files"] = sorted(changed)
    record["unexpected_diffs"] = sorted(unexpected)
    record["verdict"] = "PASS" if ok else "FAIL"
    INTEGRITY.write_text(json.dumps(record, indent=2))
    # The kernel re-verifies hashes on Kaggle, so the manifest ships inside
    # the bundle too (written AFTER the walk, so it is not in changed_files —
    # same convention as build_bundle_f1m.py).
    (BUNDLE / INTEGRITY.name).write_text(json.dumps(record, indent=2))

    n_ident = sum(1 for v in record["files"].values() if v["identical"])
    print(f"[{arm}] byte-identical files: {n_ident}/{len(record['files'])}")
    print(f"[{arm}] changed files:        {sorted(changed)}")
    print(f"[{arm}] armp checkpoint:      {'MATCH' if ck_armp_sha == ARMP_SHA else 'MISMATCH'}")
    print(f"[{arm}] e3-final checkpoint:  {'MATCH' if ck_e3_sha == E3_SHA else 'MISMATCH'}")
    print(f"[{arm}] verdict:              {record['verdict']}")
    if not ok:
        if unexpected:
            print(f"[{arm}] UNEXPECTED DIFFS: {sorted(unexpected)}")
        if missing_required:
            print(f"[{arm}] MISSING REQUIRED DIFFS: {sorted(missing_required)}")
        sys.exit(1)
    return record


def check_inter_arm() -> None:
    """bundle_l1c vs bundle_l1m must differ ONLY in finetune + marker."""
    c_files = {p.relative_to(HERE / "bundle_l1c").as_posix()
               for p in (HERE / "bundle_l1c").rglob("*") if p.is_file()}
    m_files = {p.relative_to(HERE / "bundle_l1m").as_posix()
               for p in (HERE / "bundle_l1m").rglob("*") if p.is_file()}
    # The inside-bundle integrity manifests necessarily embed per-arm names.
    ignore = {"source_integrity_l1c.json", "source_integrity_l1m.json"}
    diff = set()
    for rel in sorted((c_files | m_files) - ignore):
        cp, mp = HERE / "bundle_l1c" / rel, HERE / "bundle_l1m" / rel
        if not (cp.is_file() and mp.is_file()) or sha256(cp) != sha256(mp):
            diff.add(rel)
    print(f"inter-arm diff (excl. self-describing manifests): {sorted(diff)}")
    allowed = {"scripts/finetune_pilot.py", "BUNDLE_MARKER.json"}
    if diff != allowed:
        sys.exit(f"L1 BUILD FAIL: inter-arm diff {sorted(diff)} != {sorted(allowed)}")
    ft_c = (HERE / "bundle_l1c" / "scripts" / "finetune_pilot.py").read_text(encoding="utf-8")
    ft_m = (HERE / "bundle_l1m" / "scripts" / "finetune_pilot.py").read_text(encoding="utf-8")
    print("--- inter-arm finetune unified diff (the single loss knob) ---")
    for line in difflib.unified_diff(ft_c.splitlines(), ft_m.splitlines(),
                                     fromfile="bundle_l1c/scripts/finetune_pilot.py",
                                     tofile="bundle_l1m/scripts/finetune_pilot.py",
                                     lineterm="", n=1):
        print(line)
    print("inter-arm check: PASS (loss line + marker only)")


def main() -> None:
    for arm in ("l1c", "l1m"):
        build_arm(arm)
    check_inter_arm()


if __name__ == "__main__":
    main()
